package:
  name: psychopy
  version: "1.80.01dev"

source:
    git_url: https://github.com/psychopy/psychopy
    # git_url: https://github.com/dschreij/psychopy.git
    # git_tag: pyglet-1.2alpha1

build:
    number: 1
    script: python setup.py install

requirements:
    build:
        - python
        - numpy
        - scipy
        - matplotlib
        - wxpython
        - setuptools
        - pyopengl
        - lxml
        - openpyxl
        - ipython
        - sphinx
        - nose
        - cython
        - hdf5
        - greenlet
        - gevent
        - pyyaml
        - msgpack-python
        - pyserial
        
        - pyglet1.2 1.2alpha1
        - pyobjc-core # [osx]
        - pyobjc-framework-qtkit # [osx]
        - bdist_mpkg
        - pyserial
        - iolabs # [not linux]
        - pyxid
        - py2app # [osx]

        - labjackpython
        - portaudio
        - pysoundcard
        - pysoundfile
        
        # IOHub
        - psutil
        - pytables
        - numexpr
        - pil
        - python-xlib # [linux]
        # - opencv

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - wxpython
        - pyopengl
        - lxml
        - openpyxl
        - ipython
        - sphinx
        - nose
        - cython
        - hdf5
        - greenlet
        - gevent
        - pyyaml
        - msgpack-python
        - pyserial

        - pyglet1.2 1.2alpha1
        - pyobjc-core # [osx]
        - pyobjc-framework-qtkit # [osx]
        - bdist_mpkg
        - pyserial
        - iolabs # [not linux]
        - pyxid
        - py2app # [osx]

        - labjackpython
        - portaudio
        - pysoundcard
        - pysoudfile
        
        
        # IOHub
        # - pyobjc
        - psutil
        - pytables
        - numexpr
        - pil
        # - opencv
        
        # - parallel

test:
    # Python imports
    imports:
        - psychopy
    requires:
        - pytest

about:
    home: http://www.psychopy.org
    license: GPL3
    summary: For running psychology and neuroscience experiments
